### ISSUE TITLE
Image no Open en ZGrid

### ISSUE THREAD

**Issue by Dolls1** [mzelzoghbi/ZGallery#18]
Hello Wheen i try to open the ZGrid the app Crah with next error

`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
                                                                              at com.mzelzoghbi.zgallery.activities.ZGridActivity.onClick(ZGridActivity.java:56)
                                                                              at com.mzelzoghbi.zgallery.adapters.GridImagesAdapter$1.onClick(GridImagesAdapter.java:46)
                                                                              at android.view.View.performClick(View.java:5207)
                                                                              at android.view.View$PerformClick.run(View.java:21177)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

**Comment by dwane161** [comment]
I had the same problem, anyone can help us?

**Comment by Hemant0601** [comment]
Same problem

**Comment by charmi2636** [comment]
Yaa..I am also getting the same problem
Can anyone help?

**Comment by UniqueJoy** [comment]
i also having same problem. please fix
