### ISSUE TITLE
no such method load in Glide

### ISSUE THREAD

**Issue by charmi2636** [mzelzoghbi/ZGallery#25]
FATAL EXCEPTION: main
                                                                   Process: com.yash.yps.kvls, PID: 18673
                                                                   java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.yash.yps.kvls-1/base.apk:classes2.dex)
                                                                       at com.mzelzoghbi.zgallery.adapters.GridImagesAdapter.onBindViewHolder(GridImagesAdapter.java:39)
                                                                       at com.mzelzoghbi.zgallery.adapters.GridImagesAdapter.onBindViewHolder(GridImagesAdapter.java:19)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                       at android.view.View.layout(View.java:16653)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                       at android.view.View.layout(View.java:16653)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                       at android.view.View.layout(View.java:16653)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                                       at android.view.View.layout(View.java:16653)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                       at android.view.View.layout(View.java:16653)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                       at android.view.View.layout(View.java:16653)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2680)
                                                                       at android.view.View.layout(View.java:16653)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2198)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1958)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6045)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                   	at android.view.Choreographer$Fr

**Comment by avjinder** [comment]
I believe the developer has abandoned this library, since they've paid no attention at all to this. I'd advise using a different library.

**Comment by yashc1998** [comment]
are there any alternatives to this library?

**Comment by UniqueJoy** [comment]
> I believe the developer has abandoned this library, since they've paid no attention at all to this. I'd advise using a different library.

Is There any alternative ? @avjinder

**Comment by UniqueJoy** [comment]
@charmi2636 same problem happening

**Comment by avjinder** [comment]
@UniqueJoy are you importing a newer version of Glide in your project? 
ZGallery seems to be using an older version(4.3.1), and Glide had some breaking changes in the releases after that. 
You could fork this project, update the Glide version and make the required changes.

**Comment by UniqueJoy** [comment]
@avjinder i am not importing glide. It is as it is within the zgallery library..
