### ISSUE TITLE
When opening an image, activity crashes

### ISSUE THREAD

**Issue by CatMonster** [mzelzoghbi/ZGallery#26]
When click on image activity crashes
`02-12 17:04:48.202 7382-7382/mn.cdr.du.farnext E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: mn.cdr.du.farnext, PID: 7382
                                                                 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
                                                                     at com.mzelzoghbi.zgallery.activities.ZGridActivity.onClick(ZGridActivity.java:56)
                                                                     at com.mzelzoghbi.zgallery.adapters.GridImagesAdapter$1.onClick(GridImagesAdapter.java:46)
                                                                     at android.view.View.performClick(View.java:6294)
                                                                     at android.view.View$PerformClick.run(View.java:24770)
                                                                     at android.os.Handler.handleCallback(Handler.java:790)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

I have used this code https://github.com/mzelzoghbi/ZGallery#grid-list-builder inside a onclick listener

**Comment by itsLeonR** [comment]
### Same Error Here
Im facing this Error too, im using Android Studio 3.0.1. 
The Sample Code with the DummyImageList produces the same error. Im calling the methode via onClick from XML.

**Comment by UniqueJoy** [comment]
me also having same issue.. activity crashes onclick image
