### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by NikhilBorad** [mzelzoghbi/ZGallery#5]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setVisibility(int)' on a null object reference

**Comment by mzelzoghbi** [comment]
@NikhilBorad can you tell me the steps how to reproduce it ?

**Comment by qwert2603** [comment]
I have the same.

````
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setVisibility(int)' on a null object reference
                                                                              at com.mzelzoghbi.zgallery.activities.BaseActivity.onCreate(BaseActivity.java:41)
                                                                              at android.app.Activity.performCreate(Activity.java:6112)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                              at android.os.Looper.loop(Looper.java:194) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5631) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
````

The code is:
````
        ZGallery.with(activity, ArrayList(photoURLs))
                .setToolbarTitleColor(ZColor.WHITE)
                .setGalleryBackgroundColor(ZColor.WHITE)
                .setToolbarColorResId(R.color.colorPrimary)
                .setTitle("Zak Gallery")
                .show()
````

(inside fragment)

**Comment by sajorahasan** [comment]
I'm also facing the same issue when i try to open image from Grid
FATAL EXCEPTION: main
                                                                             Process: com.ingridtech.ingridshaadi, PID: 20769
                                                                             java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
                                                                                 at com.mzelzoghbi.zgallery.activities.ZGridActivity.onClick(ZGridActivity.java:56)
                                                                                 at com.mzelzoghbi.zgallery.adapters.GridImagesAdapter$1.onClick(GridImagesAdapter.java:46)
                                                                                 at android.view.View.performClick(View.java:5637)
                                                                                 at android.view.View$PerformClick.run(View.java:22429)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by mzelzoghbi** [comment]
I will check that and fix it by this week end. Thanks

**Comment by sajorahasan** [comment]
Thank you

**Comment by sajorahasan** [comment]
Can you also please implement feature to share image

**Comment by molexx** [comment]
This might be because your main project has a layout file called `activity_gallery.xml`. If so, try renaming it.

**Comment by mzelzoghbi** [comment]
@NikhilBorad sorry for being so late, can you try version `0.3.1` ?

**Comment by Hemant0601** [comment]
Not fixed, I am still getting this on image click on version 0.3.1

**Comment by UniqueJoy** [comment]
Not fixed on 0.3.1.. calling ZGrid / ZGallery , crashes activity @mzelzoghbi
